### ISSUE TITLE
kawagoe で node-mapbox-gl-native が動くのか検証

### ISSUE THREAD

**Issue by hfu** [un-vector-tile-toolkit/kawagoe#5]
```zsh
$ ssh pi@raspberrypi.local 
$ cd kawagoe
$ rake docker:run
# mkdir tmp
# cd tmp
# npm install @mapbox/mapbox-gl-native

> @mapbox/mapbox-gl-native@5.0.2 install /root/tmp/node_modules/@mapbox/mapbox-gl-native
> node-pre-gyp install --fallback-to-build=false

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v5.0.2/node-v64-linux-arm-Release.tar.gz
node-pre-gyp ERR! stack     at PassThrough.<anonymous> (/root/tmp/node_modules/node-pre-gyp/lib/install.js:137:27)
node-pre-gyp ERR! stack     at PassThrough.emit (events.js:203:15)
node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (/root/tmp/node_modules/needle/lib/needle.js:488:9)
node-pre-gyp ERR! stack     at Object.onceWrapper (events.js:286:20)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:198:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:442:20)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:198:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:288:12)
node-pre-gyp ERR! System Linux 4.19.93-v7l+
node-pre-gyp ERR! command "/usr/bin/node" "/root/tmp/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /root/tmp/node_modules/@mapbox/mapbox-gl-native
node-pre-gyp ERR! node -v v10.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v5.0.2/node-v64-linux-arm-Release.tar.gz
npm WARN enoent ENOENT: no such file or directory, open '/root/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @mapbox/mapbox-gl-native@5.0.2 install: `node-pre-gyp install --fallback-to-build=false`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @mapbox/mapbox-gl-native@5.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-07T22_04_58_093Z-debug.log
```

**Comment by smellman** [comment]
https://github.com/mapbox/mapbox-gl-native/blob/master/package.json#L52
`--failback-to-build=false` option may disable install for arm...

**Comment by smellman** [comment]
```
docker run -ti --rm -p 9966:9966 unvt/kawagoe
git clone https://github.com/mapbox/mapbox-gl-native.git
cd mapbox-gl-native
git submodule update --init --recursive
vim package.json
# remove --fallback-to-build=false
npm install
# fail
apk add cmake curl-dev icu-dev jpeg-dev mesa-dev libva-glx-dev
cmake . -B build
# fail orz
```
